services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: chakoo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chakoo
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
